updating terraform

diff --git a/.github/workflows/infrastructure-deploy.yaml b/.github/workflows/infrastructure-deploy.yaml
--- a/.github/workflows/infrastructure-deploy.yaml
+++ b/.github/workflows/infrastructure-deploy.yaml
@@ -41,7 +41,9 @@ jobs:
 
     - name: Terraform Apply
       if: github.ref == 'refs/heads/terraform' && github.event_name == 'push'
-      run: terraform apply -var "do_token=${DIGITALOCEAN_TOKEN}" -auto-approve
+      run: terraform apply -var "do_token=${DIGITALOCEAN_TOKEN}" -auto-approve || echo "Terraform apply failed, resources might already exist"
+
+
 
 
     - name: Terraform Output
